AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Stage:
    Type: "String"
    AllowedValues:
      - dev
      - prod

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Stage}2-staking-cluster"
      # No capacity providers necessary for EC2
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      # CONFIGURE LOGGING HERE
  ECSService:
      Type: AWS::ECS::Service
      Properties:
        Cluster: !Sub "${Stage}2-staking-cluster"
        DeploymentConfiguration: 
          DeploymentConfiguration
        DeploymentController: 
          DeploymentController
        DesiredCount: 1
        EnableECSManagedTags: true
        EnableExecuteCommand: true
        HealthCheckGracePeriodSeconds: Integer
        LaunchType: EC2
        NetworkConfiguration: 
          NetworkConfiguration
        PlacementConstraints: 
          - PlacementConstraint
        PlacementStrategies: 
          - PlacementStrategy
        SchedulingStrategy: String
        ServiceConnectConfiguration: 
          ServiceConnectConfiguration
        ServiceName: !Sub "${Stage}2_staking_service"
        ServiceRegistries: 
          - ServiceRegistry
        TaskDefinition: !Sub "${Stage}_eth_staker"
      


          # service
          # asg
          # vpc
          # subnets
          # security group
          # need io2 500 gb ssd ebs vol attached to ec2 instance
          # turn on ebs optimization
