AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Stage:
    Type: "String"
    AllowedValues:
      - dev
      - prod
  Subnet:
    Type: "String"
    NoEcho: true
  VPC:
    Type: "String"
    NoEcho: true
  DesiredCapacity:
    Type: "Number"
    Default: 1
  LatestECSOptimizedAMI:
    Description: AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id
  # SnapShot:
  #   Description: Snapshot ID
  #   Type: "String"
  #   Default: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}_staking_snapshot'


Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies: 
        - PolicyName: BackupEBSVol
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 'ec2:CreateSnapshot'
                  - 'ec2:DeleteSnapshot'
                  - 'ec2:DescribeSnapshots'
                Resource: '*'
              - Effect: Allow
                Action: 
                  - 'ec2:CreateTags'
                  # prob describe tags
                  # maybe delete?
                Resource: !Sub 'arn:aws:ec2:${AWS::Region}::snapshot/*'
              - Effect: Allow
                Action: 
                  - 'ssm:PutParameter'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}_staking_snapshot'
      RoleName: !Sub "${Stage}StakingTaskRole"
  TaskDefinition:
    DependsOn: TaskRole
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name: !Sub "${Stage}_staking_container"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${Stage}_eth_staker:latest"
          Environment:
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region
            - NAME: AWS
              Value: true
          Essential: true
          MountPoints:
            - ContainerPath: /mnt/ebs
              ReadOnly: false
              SourceVolume: EBSVol
          Interactive: true
          PseudoTerminal: true
      Cpu: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"
      Family: !Sub "${Stage}_eth_staker"
      Memory: 6144
      NetworkMode: bridge
      RequiresCompatibilities: 
        - EC2
      RuntimePlatform: 
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      TaskRoleArn: !GetAtt TaskRole.Arn
      Volumes: 
        - Host: 
            SourcePath: /mnt/ebs
          Name: EBSVol
  SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: String
        GroupName: !Sub "${Stage}_staking_sg"
        SecurityGroupEgress: 
          - CidrIp: 0.0.0.0/0
            IpProtocol: -1
        SecurityGroupIngress: 
          - CidrIp: 0.0.0.0/0
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
          - CidrIp: 0.0.0.0/0
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80
        VpcId: !Ref VPC
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Stage}-staking-cluster"
      # No capacity providers necessary for EC2
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      # ECS Execute logging is defined in Config
      # CONFIGURE LOGGING HERE
  ECSService:
      Type: AWS::ECS::Service
      DependsOn: 
        - ECSCluster
        - TaskDefinition
      Properties:
        Cluster: !Sub "${Stage}-staking-cluster"
        DeploymentConfiguration: 
          DeploymentCircuitBreaker:
            Enable: false
            Rollback: true
          MaximumPercent: 200
          MinimumHealthyPercent: 0
        DeploymentController: 
          Type: ECS
        DesiredCount: !Ref DesiredCapacity
        EnableECSManagedTags: true
        # EnableExecuteCommand: true
        # https://github.com/aws/aws-cli/issues/6242
        LaunchType: EC2
        PlacementStrategies: 
          - Type: spread
            Field: attribute:ecs.availability-zone
          - Type: spread
            Field: instanceId
        SchedulingStrategy: REPLICA
        ServiceName: !Sub "${Stage}_staking_service"
        TaskDefinition: !Sub "${Stage}_eth_staker"
  AutoScalingGroup:
    DependsOn: 
      - ECSCluster
      - LaunchTemplate
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "ECS_${Stage}_staking_ASG"
      AvailabilityZones: 
        - !Sub "${AWS::Region}d"
      CapacityRebalance: true
      DesiredCapacity: !Sub "${DesiredCapacity}"
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MaxSize: 2
      MetricsCollection: 
        - Granularity: 1Minute
      MinSize: 0
      NewInstancesProtectedFromScaleIn: false
      Tags: 
        -
          Key: Name
          Value: !Sub "ECS Instance - ${AWS::StackName}"
          PropagateAtLaunch: true
        -
          Key: Description
          Value: "This instance is the part of the Auto Scaling group which was created through Cloudformation"
          PropagateAtLaunch: true
      TerminationPolicies: 
        - Default
      VPCZoneIdentifier: 
        - !Ref Subnet
  LaunchTemplate:
    DependsOn: SecurityGroup  
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        BlockDeviceMappings:
          - 
            DeviceName: /dev/sdx
            Ebs: 
              DeleteOnTermination: true
              VolumeSize: 500
              # can't use io2 because of cost
              VolumeType: gp3
              # Iops: 10000
              # 10 - 15k is laptop/desktop SSD throughput
              # Throughput: 1000
              # SnapshotId: '{{resolve:ssm:${Stage}_staking_snapshot}}' 
              # try defining cf param as ssm param val or 'default' / pseudo AWS::NoValue
              # https://www.jforte.me/posts/create-ebs-volume-snapshot-condtions-aws-cdk/
        DisableApiStop: false
        DisableApiTermination: false
        EbsOptimized: true
        IamInstanceProfile: 
          Name: ecsInstanceRole
        # This is Amazon Linux 2023 AMI for amd64
        ImageId: !Ref LatestECSOptimizedAMI
        InstanceInitiatedShutdownBehavior: terminate
        # for spot instances
        # InstanceMarketOptions: 
        #   InstanceMarketOptions
        # # use this to specify reqs instead of instance type
        # InstanceRequirements: 
        #   InstanceRequirements
        InstanceType: t3.large
        KeyName: !Sub "${Stage}_staking_keys"
        MaintenanceOptions: 
          AutoRecovery: default
        Monitoring: 
          Enabled: true
        SecurityGroupIds: 
          - !GetAtt SecurityGroup.GroupId
        TagSpecifications: 
          - ResourceType: volume
            Tags:
              -
                Key: Name
                Value: !Sub "ECS Instance - ${AWS::StackName}"
              -
                Key: Description
                Value: "This volume is the part of the Launch Template which was created through Cloudformation"
          - ResourceType: instance
            Tags:
              -
                Key: Name
                Value: !Sub "ECS Instance - ${AWS::StackName}"
              -
                Key: Description
                Value: "This instance is the part of the Launch Template which was created through Cloudformation"
        UserData:
          "Fn::Base64": !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
            echo ECS_ENABLE_CONTAINER_METADATA=true >> /etc/ecs/ecs.config
            yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            yum install -y https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
            yum install -y aws-cfn-bootstrap hibagent 
            /opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource LaunchTemplate
            /opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource AutoScalingGroup
            /usr/bin/enable-ec2-spot-hibernation
            mkdir -p /mnt/ebs
            mkfs -t xfs /dev/sdx
            if [ $? -eq 0 ]; then
                echo "New volume initialized."
            else
                echo "Snapshot EBS volume loaded."
            fi
            mount -o nouuid /dev/sdx /mnt/ebs
            # Write volume id to volume
            awk -F' '  '{print $NF}' <<< $(/sbin/ebsnvme-id /dev/sdx -v) > /mnt/ebs/VOLUME_ID

      LaunchTemplateName: !Sub "${Stage}_launch_template"

# stop geth, beacon-node, and validators before taking snapshot
# take snapshot every 1 month - check every hour and at start if snapshot doesn't exist or snapshot is older than 30 days
# put snapshot id in ssm param
# use resolve:ssm in cf for snapshotId in ebs config
# after taking snapshot, delete snapshots that are older than 90 days
# create new iam role that allows all permissions to do this
# define role here in cf and attach to IamInstanceProfile or TaskExecutionRole in LaunchTemplate
# restart geth, beacon-node, and validators

# DO NOT ENABLE FAST RESTORE - V EXPENSIVE

# mkdir -p or python make path /mnt/ebs/.ethereum and /mnt/ebs/.eth2 if doesn't exist and no snapshot
# set geth datadir to /mnt/ebs/.ethereum

# set beacon-node and validator data dir to /mnt/ebs/.eth2