AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Stage:
    Type: "String"
    AllowedValues:
      - dev
      - prod
  Subnet:
    Type: "String"
    NoEcho: true

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Stage}2-staking-cluster"
      # No capacity providers necessary for EC2
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      # CONFIGURE LOGGING HERE
  ECSService:
      Type: AWS::ECS::Service
      Properties:
        Cluster: !Sub "${Stage}2-staking-cluster"
        DeploymentConfiguration: 
          # Alarms:
          DeploymentCircuitBreaker:
            Enable: false
            Rollback: true
          MaximumPercent: 200
          MinimumHealthyPercent: 100
        DeploymentController: 
          Type: ECS
        DesiredCount: 1
        EnableECSManagedTags: true
        EnableExecuteCommand: true
        LaunchType: EC2
        NetworkConfiguration: 
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            SecurityGroups: 
              - String
            Subnets: 
              - !Ref Subnet
        PlacementStrategies: 
          - Type: spread
            Field: attribute:ecs.availability-zone
          - Type: spread
            Field: instanceId
        SchedulingStrategy: REPLICA
        # ServiceConnectConfiguration: 
        #   ServiceConnectConfiguration
        ServiceName: !Sub "${Stage}2_staking_service"
        # ServiceRegistries: 
        #   - ServiceRegistry
        TaskDefinition: !Sub "${Stage}_eth_staker"
      


          # service
          # ec2 instance - create
          # asg - create
          # vpc - just pass in
          # subnets - just pass in
          # security group - try to create
          # need io2 500 gb ssd ebs vol attached to ec2 instance
          # turn on ebs optimization
